In [57]:
import numpy as np
import pandas as pd

In [58]:
# Creating a DataFrame

In [59]:
data = {
    'Name': ['Arka', 'Aditya', 'Anurag', 'Lakshya'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [75000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [60]:
df

      Name  Age      City  Salary
0     Arka   28  New York   75000
1   Aditya   34     Paris   70000
2   Anurag   29    Berlin   62000
3  Lakshya   42    London   85000

In [61]:
data_list = [
    ['Arka', 28, 'New York', 65000],
    ['Aditya', 34, 'Paris', 70000],
    ['Anurag', 29, 'Berlin', 62000],
    ['Lakshay', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns=columns)
df2

      Name  Age      City  Salary
0     Arka   28  New York   65000
1   Aditya   34     Paris   70000
2   Anurag   29    Berlin   62000
3  Lakshay   42    London   85000

In [62]:
# Selection and Indexing of Columns

In [63]:
df2["Name"]

0       Arka
1     Aditya
2     Anurag
3    Lakshay
Name: Name, dtype: object

In [64]:
df2['Salary']

0    65000
1    70000
2    62000
3    85000
Name: Salary, dtype: int64

In [65]:
df2[['Name', 'Salary']]

      Name  Salary
0     Arka   65000
1   Aditya   70000
2   Anurag   62000
3  Lakshay   85000

In [66]:
# Creating a new column

In [67]:
df2['Designation'] = ['Data Analyst', 'SDE', 'Marketing Head', 'Project Manager']
df2

      Name  Age      City  Salary      Designation
0     Arka   28  New York   65000     Data Analyst
1   Aditya   34     Paris   70000              SDE
2   Anurag   29    Berlin   62000   Marketing Head
3  Lakshay   42    London   85000  Project Manager

In [68]:
# Removing Columns

In [69]:
df2.drop('Age', axis=1, inplace=True)      # inplace is used for permanent removal of columns
df2

      Name      City  Salary      Designation
0     Arka  New York   65000     Data Analyst
1   Aditya     Paris   70000              SDE
2   Anurag    Berlin   62000   Marketing Head
3  Lakshay    London   85000  Project Manager

In [70]:
df2.drop(['Name', 'City'], axis=1)

   Salary      Designation
0   65000     Data Analyst
1   70000              SDE
2   62000   Marketing Head
3   85000  Project Manager

In [71]:
df2.drop(2, axis=0)

      Name      City  Salary      Designation
0     Arka  New York   65000     Data Analyst
1   Aditya     Paris   70000              SDE
3  Lakshay    London   85000  Project Manager

In [72]:
# Selecting Rows

In [73]:
df2

      Name      City  Salary      Designation
0     Arka  New York   65000     Data Analyst
1   Aditya     Paris   70000              SDE
2   Anurag    Berlin   62000   Marketing Head
3  Lakshay    London   85000  Project Manager

In [74]:
df2.loc[3]

Name                   Lakshay
City                    London
Salary                   85000
Designation    Project Manager
Name: 3, dtype: object

In [75]:
df2.loc[[0, 3]]

      Name      City  Salary      Designation
0     Arka  New York   65000     Data Analyst
3  Lakshay    London   85000  Project Manager

In [76]:
df2.iloc[2]

Name                   Anurag
City                   Berlin
Salary                  62000
Designation    Marketing Head
Name: 2, dtype: object

In [77]:
# Selecting subsets of rows and columns

In [78]:
df2.loc[[0, 1]][['Name', 'Designation']]

     Name   Designation
0    Arka  Data Analyst
1  Aditya           SDE

In [79]:
df2.loc[[2, 3]][['Name', 'City']]

      Name    City
2   Anurag  Berlin
3  Lakshay  London

In [80]:
# Conditional selection

In [81]:
df2

      Name      City  Salary      Designation
0     Arka  New York   65000     Data Analyst
1   Aditya     Paris   70000              SDE
2   Anurag    Berlin   62000   Marketing Head
3  Lakshay    London   85000  Project Manager

In [83]:
df2[(df2['Salary'] > 65000) & (df2['City'] == "Paris")]

     Name   City  Salary Designation
1  Aditya  Paris   70000         SDE