In [28]:
import numpy as np
import pandas as pd

In [29]:
# Finding missing data

In [30]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [31]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [32]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [33]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [34]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [50]:
# Removing missing data

In [36]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [37]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [42]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [43]:
# Filling the missing data

In [44]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [45]:
df.fillna(1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  1.0
2  1.0  3  3.0  1.0
3  4.0  4  1.0  1.0
4  5.0  5  1.0  5.0

In [47]:
values = {'A':3, 'B':1, 'C':5, 'D':4}
df.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  4.0
2  3.0  3  3.0  4.0
3  4.0  4  5.0  4.0
4  5.0  5  5.0  5.0

In [48]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [49]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0